import type { LucideIcon } from 'lucide-react';
import {
  Armchair,
  Baby,
  BookOpen,
  Box,
  Car,
  Dumbbell,
  Gamepad2,
  Flower2,
  Gift,
  Hammer,
  Headphones,
  Heart,
  Home,
  KeyRound,
  LayoutGrid,
  Music,
  Package,
  Paintbrush,
  PawPrint,
  Shirt,
  ShoppingBag,
  Sparkles,
  Trees,
  Watch,
  Wrench,
} from 'lucide-react';

/** Lucide icon per category slug (Facebook Marketplace–style browse). */
export function marketplaceCategoryIcon(slug: string): LucideIcon {
  const map: Record<string, LucideIcon> = {
    'antiques-collectibles': Sparkles,
    'arts-crafts': Paintbrush,
    baby: Baby,
    'books-films-music': BookOpen,
    'car-parts': Wrench,
    'childrenswear-baby': Shirt,
    diy: Hammer,
    electronics: Headphones,
    'free-community': Gift,
    furniture: Armchair,
    'garage-sale': Box,
    'health-beauty': Heart,
    'home-kitchen': Home,
    'jewellery-watches': Watch,
    'luggage-bags': ShoppingBag,
    menswear: Shirt,
    miscellaneous: Package,
    'musical-instruments': Music,
    'patio-garden': Trees,
    'pet-supplies': PawPrint,
    'properties-rent': Home,
    'properties-sale': KeyRound,
    'sporting-goods': Dumbbell,
    'toys-games': Gamepad2,
    vehicles: Car,
    womenswear: Shirt,
  };
  return map[slug] || LayoutGrid;
}
